# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4N5pdMpt9SUd81xjnT9pVvAxzApUec0
"""
!pip install python-bcb

import pandas as pd
from bcb import sgs
from datetime import datetime  

# Definindo as séries para IPCA, Dólar e Selic
cod_dados = {'ipca': 433, 'dolar': 3698, 'selic': 4390, 'exportacoes': 22708}

# Puxando os códigos do dicionário cod_dados com início em 2015
dados = sgs.get(cod_dados, start='2015-01-01', end=datetime.today().strftime('%Y-%m-%d'))
# Removing inplace=True to get a DataFrame assigned to df_dados
df_dados = dados.reset_index() 

# Convertendo os dados em arquivo CSV
df_dados.to_csv('dados.csv')