# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qnOETZP33qt1NVIwbXBfx0p7TeYbmbm
"""

!pip install python-bcb

from bcb import sgs
import datetime
import pandas as pd
import plotly.express as px

# Definir tempo
hoje = datetime.date.today()
dt_inicio = hoje - datetime.timedelta(days=365)

# Dicionário (Taxa de câmbio, Exportações, Importações, SELIC)
series = {'Dólar': 1,'Euro': 21619,'Iene': 21621,'Exportações': 13966,'Importações': 13962,'SELIC': 432}

df = sgs.get(series, start=dt_inicio, end=hoje).reset_index()

df.rename(columns={df.columns[0]: 'Data'}, inplace=True)


df.fillna(df.mean(numeric_only=True), inplace=True) #Preencher oque falta com média do periodo

cambio_columns = ['Dólar', 'Euro', 'Iene']
fig_cambio = px.line(df, x='Data', y=cambio_columns, title='Taxas de Câmbio: Dólar, Euro e Iene')
fig_cambio.update_layout(
    xaxis_title='Data',
    yaxis_title='Valor',
    template='seaborn'
)
fig_cambio.show()

fig_selic = px.line(df, x='Data', y='SELIC', title='Taxa SELIC')
fig_selic.update_layout(
    xaxis_title='Data',
    yaxis_title='Valor',
    template='seaborn'
)
fig_selic.show()

export_import_columns = ['Exportações', 'Importações']
fig_export_import = px.line(df, x='Data', y=export_import_columns, title='Exportações e Importações')
fig_export_import.update_layout(
    xaxis_title='Data',
    yaxis_title='Valor',
    template='seaborn'
)
fig_export_import.show()


df.to_csv(f'import_export_{dt_inicio}_{hoje}.csv', index=False) #Exportar para CSV