# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4N5pdMpt9SUd81xjnT9pVvAxzApUec0
"""

!pip install python-bcb

import pandas as pd
from bcb import sgs  

# Definindo as séries para IPCA, Dólar e Selic
ipca = sgs.get({'ipca': 433}, start='2023-01-01', end='2025-03-01')  # IPCA
dolar = sgs.get({'dolar': 1}, start='2023-01-01', end='2025-03-01')   # Dólar
selic = sgs.get({'selic': 432}, start='2023-01-01', end='2025-03-01')   # Selic
exportacoes = sgs.get({'exportacoes': 13966}, start='2023-01-03', end='2025-03-01')  # Exportações

# Garantindo que todas as séries tenham a mesma data final
ipca = ipca[:data_final]
dolar = dolar[:data_final]
selic = selic[:data_final]
exportacoes = exportacoes[:data_final]

# Normalizando as séries para ficarem na mesma escala
ipca_normalizado = ipca['ipca'] * 4  # Multiplicando por 4 para ajustar a escala do IPCA
dolar_normalizado = dolar['dolar'] / 5  # Dividindo por 5 para ajustar a escala do Dólar
selic_normalizado = selic['selic'] / 10  # Multiplicando por 20 para ajustar a escala da Selic
exportacoes_normalizadas = exportacoes['exportacoes'] / 1000  # Dividindo por 1000 para ajustar a escala das exportações

# Aplicando média móvel (suavização)
window_size = 10  # Definindo o tamanho da janela para a média móvel (5 períodos)
ipca_suavizado = ipca_normalizado.rolling(window=window_size).mean()
dolar_suavizado = dolar_normalizado.rolling(window=window_size).mean()
selic_suavizado = selic_normalizado.rolling(window=window_size).mean()
exportacoes_suavizadas = exportacoes_normalizadas.rolling(window=window_size).mean()